# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scanner.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'scanner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rscanner.proto\"U\n\x0bScanRequest\x12\x1d\n\x15path_within_directory\x18\x01 \x01(\t\x12\x12\n\nchunk_data\x18\x02 \x01(\x0c\x12\x13\n\x0b\x65nd_of_file\x18\x03 \x01(\x08\";\n\nScanResult\x12\x1d\n\x15path_within_directory\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2=\n\x0b\x46ileService\x12.\n\rScanDirectory\x12\x0c.ScanRequest\x1a\x0b.ScanResult(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scanner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCANREQUEST']._serialized_start=17
  _globals['_SCANREQUEST']._serialized_end=102
  _globals['_SCANRESULT']._serialized_start=104
  _globals['_SCANRESULT']._serialized_end=163
  _globals['_FILESERVICE']._serialized_start=165
  _globals['_FILESERVICE']._serialized_end=226
# @@protoc_insertion_point(module_scope)
