FROM clamav/clamav:latest

RUN sed -i 's/^TCPSocket.*/TCPSocket 3310/' /etc/clamav/clamd.conf && \
    sed -i 's/^TCPAddr.*/TCPAddr 0.0.0.0/' /etc/clamav/clamd.conf

EXPOSE 3310

CMD ["clamd", "--foreground=true"]
